apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-controller-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    pingdom.controller.yad2/apply: "true"
    pingdom.controller.yad2/encryption: "true"
    pingdom.controller.yad2/resolution: "1"
  name: pingdom-controller
spec:
  rules:
    - host: my.domain.io
      http:
        paths:
          - backend:
              serviceName: kubernetes-dashboard
              servicePort: https
            path: /